---
- name: Ensure scripts directory exists
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    owner: clickhouse
    group: clickhouse
    mode: '0755'

- name: Check if clickhouse-backup is already installed
  ansible.builtin.shell: dpkg -l clickhouse-backup
  register: clickhouse_backup_installed
  ignore_errors: true

- name: Download ClickHouse backup tool .deb package
  ansible.builtin.get_url:
    url: "https://github.com/Altinity/clickhouse-backup/releases/download/v2.6.3/clickhouse-backup_2.6.3_amd64.deb"
    dest: "/tmp/clickhouse-backup.deb"
  when: clickhouse_backup_installed.rc != 0

- name: Install ClickHouse backup tool using dpkg
  ansible.builtin.command:
    cmd: "dpkg -i /tmp/clickhouse-backup.deb"
  when: clickhouse_backup_installed.rc != 0

- name: Install AWS CLI
  ansible.builtin.package:
    name: "{{ 'awscli' if ansible_os_family == 'Debian' else 'aws-cli' }}"
    state: present

- name: Deploy backup script
  ansible.builtin.template:
    src: backup_to_s3.sh.j2
    dest: /opt/scripts/backup_to_s3.sh
    mode: '0755'
    owner: clickhouse
    group: clickhouse

- name: Add cron job for ClickHouse backup to S3
  ansible.builtin.cron:
    name: "ClickHouse Backup to S3"
    user: clickhouse
    minute: "0"
    hour: "3"
    job: "/opt/scripts/backup_to_s3.sh"

- name: Deploy restore backup script
  ansible.builtin.template:
    src: restore_from_backup.sh.j2
    dest: /opt/scripts/restore_from_backup.sh
    mode: '0755'
    owner: clickhouse
    group: clickhouse
