---

- name: Install ClickHouse
  ansible.builtin.include_tasks: install.yml

- name: Configure SSL ClickHouse
  ansible.builtin.include_tasks: ssl.yml
  when: clickhouse_ssl_enabled

- name: Configure ClickHouse
  ansible.builtin.include_tasks: configure.yml

- name: Configure ZooKeeper
  ansible.builtin.include_tasks: zookeeper.yml
  when: clickhouse_zookeeper_enabled

- name: Configure backup for ClickHouse
  ansible.builtin.include_tasks: backup.yml
