---

- name: Install ZooKeeper package
  ansible.builtin.package:
    name: zookeeperd
    state: present

- name: Ensure ZooKeeper directory exists
  ansible.builtin.file:
    path: /etc/zookeeper
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: '0755'

- name: Upload ZooKeeper configuration
  ansible.builtin.template:
    src: zookeeper_config.xml.j2
    dest: /etc/zookeeper/zoo.cfg
    owner: zookeeper
    group: zookeeper
    mode: '0644'

- name: Ensure ZooKeeper service is enabled and started
  ansible.builtin.service:
    name: zookeeper
    state: started
    enabled: true
